### ISSUE TITLE
Add Source Code Pro font

### ISSUE THREAD

**Issue by brendanorourke** [brendanorourke/dotfiles#70]
### Tasks

- [x] Add script (1) to `/scripts/`
- [x] Instantiate script on `init`
- [x] Modify configs to default to Source Code Pro

### Snippets

1. _Install_
```bash
#!/bin/sh
# Userland mode (~$USER/), (~/).

# ~/.fonts is now deprecated and that
#FONT_HOME=~/.fonts
# ~/.local/share/fonts should be used instead
FONT_HOME=~/.local/share/fonts

echo "installing fonts at $PWD to $FONT_HOME"
mkdir -p "$FONT_HOME/adobe-fonts/source-code-pro"
# find "$FONT_HOME" -iname '*.ttf' -exec echo '{}' \;

(git clone \
   --branch release \
   --depth 1 \
   'https://github.com/adobe-fonts/source-code-pro.git' \
   "$FONT_HOME/adobe-fonts/source-code-pro" && \
fc-cache -f -v "$FONT_HOME/adobe-fonts/source-code-pro")
```
